apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mbd-ca
  namespace: mbd-infra
spec:
  isCA: true
  commonName: mbd-ca
  secretName: mbd-ca-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mbd-ca-issuer
spec:
  ca:
    secretName: mbd-ca-secret
