apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: mbd-infra
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_NODE_ID: "1"
  CLUSTER_ID: "5c8f3e9f-7b2a-4c1d-9e8f-1a2b3c4d5e6f"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-0.kafka.mbd-infra.svc.cluster.local:9093"
  KAFKA_LISTENERS: "PLAINTEXT://:9092,BROKER://:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.mbd-infra.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "BROKER"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_LOG_SEGMENT_BYTES: "1073741824"
  KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
