apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-topic-creator
  namespace: mbd-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-topic-creator
  namespace: mbd-infra
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-topic-creator
  namespace: mbd-infra
subjects:
  - kind: ServiceAccount
    name: kafka-topic-creator
    namespace: mbd-infra
roleRef:
  kind: Role
  name: kafka-topic-creator
  apiGroup: rbac.authorization.k8s.io
