apiVersion: v1
kind: ResourceQuota
metadata:
  name: mbd-quota
  namespace: mbd
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "12"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
