apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbd-namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:edwinbulter/mbd.git
    targetRevision: main
    path: infrastructure/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
