apiVersion: v1
kind: Service
metadata:
  name: apim-gateway
  namespace: mbd
spec:
  selector:
    app: apim-gateway
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8443
      name: https
  type: ClusterIP
