apiVersion: apps/v1
kind: Deployment
metadata:
  name: fund-service
  namespace: mbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fund-service
  template:
    metadata:
      labels:
        app: fund-service
    spec:
      containers:
        - name: fund-service
          image: fund-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
