apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: z-admin-frontend
  namespace: mbd
spec:
  hosts:
    - "admin.mbd.local"
  gateways:
    - mbd/mbd-gateway
  http:
    - route:
        - destination:
            host: admin-frontend
            port:
              number: 80
