apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: fund-service
  namespace: mbd
spec:
  hosts:
    - "customer.mbd.local"
    - "admin.mbd.local"
  gateways:
    - mbd/mbd-gateway
  http:
    - match:
        - uri:
            prefix: /api/funds
      corsPolicy:
        allowOrigins:
          - exact: https://customer.mbd.local
          - exact: https://admin.mbd.local
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - DELETE
        allowHeaders:
          - "*"
        maxAge: 24h
      route:
        - destination:
            host: fund-service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /swagger-ui
      route:
        - destination:
            host: fund-service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /v3/api-docs
      route:
        - destination:
            host: fund-service
            port:
              number: 8080
